---
development:
  repositories:
    default:
      adapter:  mysql
      database: oursignal

rake:
  repositories:
    default:
      adapter:  mysql
      database: oursignal

test:
  repositories:
    default:
      adapter:  mysql
      database: oursignal_test
      username: root
      host:     localhost

staging:
  repositories:
    default:
      adapter:  mysql
      database: oursignal_staging
      username: root
      host:     localhost
