---
development: &defaults
  adapter:  mysql
  database: oursignal
  host: localhost

test:
  <<:       *defaults
  database: oursignal_test

staging:
  <<:       *defaults
  database: oursignal_staging
  username: root

production:
  <<:       *defaults
  database: oursignal
  username: root

rake:
  <<: *defaults
