---
development: &defaults
  adapter:  mysql
  database: oursignal
  host:     127.0.0.1
  port:     3306

test:
  <<:       *defaults
  database: oursignal_test

staging:
  <<:       *defaults
  database: oursignal_staging
  username: root

production:
  <<:       *defaults
  database: oursignal
  username: root

rake:
  <<: *defaults
